### ISSUE TITLE
Demo Errors

### ISSUE THREAD

**Issue by oravecz** [webcomponents/angular-interop#2] opened 2016-11-01 17:15 UTC
At least on Chrome 48

https://rawgit.com/webcomponents/angular-interop/06d5a154ba295a3d2fd6ab79ddbf6a7405f6a0e8/angular2/index.html

Throws exceptions
```
https://polygit.org/components/webcomponentsjs/webcomponents-lite.js Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
https://polygit.org/components/paper-input/paper-input.html Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
polymer.component.html:19 Uncaught ReferenceError: Polymer is not defined
logger:20 TypeScript transpiling to CommonJS, consider setting module: "system" in typescriptOptions to transpile directly to System.register format
core.umd.js:241 Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
```

**Comment by Splaktar** [comment] 2016-11-19 00:40
Not seeing that on Chrome 54.

**Comment by manekinekko** [comment] 2017-02-16 13:57
I'm closing this issue since it's not reproducible.

**Closed as completed by manekinekko** 2017-02-16 13:57 UTC
